In [2]:
import pandas as pd

# Данные
data = {
    'city': ['Jacksonville', 'Jacksonville', 'Jacksonville', 'Jacksonville', 'Jacksonville',
             'ElPaso', 'ElPaso', 'ElPaso', 'ElPaso', 'ElPaso'],
    'month': ['January', 'February', 'March', 'April', 'May',
              'January', 'February', 'March', 'April', 'May'],
    'temperature': [13, 23, 38, 5, 34, 20, 6, 26, 2, 43]
}

# Создание DataFrame
df = pd.DataFrame(data)

# Вывод DataFrame
df

           city     month  temperature
0  Jacksonville   January           13
1  Jacksonville  February           23
2  Jacksonville     March           38
3  Jacksonville     April            5
4  Jacksonville       May           34
5        ElPaso   January           20
6        ElPaso  February            6
7        ElPaso     March           26
8        ElPaso     April            2
9        ElPaso       May           43

In [7]:
# Создаем pivot таблицу: строки – даты, столбцы – продукты, значения – продажи
pivot_table = df.pivot(index='month', columns='city', values='temperature')
print("Базовая pivot таблица:")
pivot_table

Базовая pivot таблица:

city      ElPaso  Jacksonville
month
April          2             5
February       6            23
January       20            13
March         26            38
May           43            34